[".zprezto"]
	type = "archive"
  url = "https://github.com/sorin-ionescu/prezto/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".zprezto/modules/syntax-highlighting/external"]
	type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".zprezto/modules/history-substring-search/external"]
	type = "archive"
  url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/alacritty"]
  type = "archive"
  url = "https://github.com/alacritty/alacritty-theme/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/themes/**"]
[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/**"]
[".hammerspoon/Spoons"]
  type = "archive"
  url = "https://github.com/peterklijn/hammerspoon-shiftit/releases/latest/download/ShiftIt.spoon.zip"
  exact = true
  stripComponents = 0
  refreshPeriod = "168h"
  include = ["*/**"]

