apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNRi9la0JLZ0ZuRmp3NTlQeU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalF3T1RJd01UZ3lNakF5V2hjTk16UXdPVEl3TVRneQpNakF5V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBNi9KUFFqVTZLbDRoMVFML3RoRmNrckJETklhNWNSTnNaSWJDak00OUZtb1oKMzJNVms0NU9JV29XbUkxYVQvNm5SYmdRS3FBQWRDbDJ4NFRMQXpnY0JqOEVxelAvcWVwOEJGemFmdWNDRDZsVQpPTHFsUGRKUU5GVExUUjlzRnFqbmdIZkNna0kzNW5hLzNyWGZZYkFJY3kwWHNOUVlxKzlYYzhsYURERlVBUWJRCkk4ckhsd3Bha1JURFBSd25YSmNGb0o0anBZckh5OVpUYTNEbTBaRGNDY09ldWxmeXBTK3RkM2ZsemhBSEZMOU8KbHVxWTY5c01MVm12eGZ1WVNLQW4zWCt4ZEJhbkJlVERhaEVLazgrcUlRTHdHT1RuWDJLeThQTlU0YzY5aFhWOQpDZjkwc3N6OEljRWFZTDlxd09SL0dkWm1TWGZtS0lKbjRrQXdDeUVUL3dJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRBT2Y0ajBUOFgydDhFUlIKeWpNSm1uUzNZckV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU9xaHZlS1hheE9rdVNQaEhQOGdCdG0wQTlTNApvMHRkck1IUmtyT0pMTXRtV1QxUnp1bHZBeHBZRXlhaE5YVzR6RDdVdW13Tis4MUcyczhxekhNQWkzNlJvT0ZoClBPUHc3alQyYllyNnUxck9NdUlNV2IzbWI5K0xjZzU1VGZrN2QzRnV4MDF6a013aENvNVpJSDJGWEFFYXpyeHMKVVRSUDRpSW01Z1JKUGs4elc0SlNEcExPZllxQjhraDlUcE9NRzRWaXpiUGNWQjhuYUhCNlV3R0s4MFBKcTh1TwpvdUgxVHF3Q2tCbGxMelJaNW1CZ3lHelplTEFNajBjTDY3MHVhWmZEZEhDNTYxclpvenRwM3A3OVFtSXNvUHRQCis0UVN4SUxNM2JhNTdZeHc2U1pwMGxPWUhHU0c4dllkZGN4aGp3Y1J5eThpVnY3TGVlOUxaVzFxbTJZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api-k8s-sparetimecoders-c-4lf7b7-7e84e854fb609201.elb.eu-west-1.amazonaws.com
    tls-server-name: api.internal.k8s.sparetimecoders.com
  name: k8s.sparetimecoders.com
contexts:
- context:
    cluster: k8s.sparetimecoders.com
    user: k8s.sparetimecoders.com
  name: k8s.sparetimecoders.com
current-context: k8s.sparetimecoders.com
kind: Config
preferences: {}
users:
- name: k8s.sparetimecoders.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - k8s.sparetimecoders.com
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
