registry:
  ecr:
    url: 892944254496.dkr.ecr.eu-west-1.amazonaws.com

targets:
  local:
    context: kind-lifeinside
    namespace: default
  staging:
    context: k8s.staging.lifeinside.io
    namespace: default
  prod:
    context: k8s.lifeinside.io
    namespace: default