apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU5yYjAydWNzWUFEMmNxUXhxb3VNZlF3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa016UTVZVFExWXpndE1qY3pZUzAwTVRWaUxXRm1ZMlV0TXpOaE16bG1NR1UzTldJNApNQjRYRFRJd01EVXhOVEEzTkRrMU5Wb1hEVEkxTURVeE5EQTRORGsxTlZvd0x6RXRNQ3NHQTFVRUF4TWtNelE1CllUUTFZemd0TWpjellTMDBNVFZpTFdGbVkyVXRNek5oTXpsbU1HVTNOV0k0TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMkNwaW1paTVHZG9QVVRBRTBSbGQxRTdlREZ6R2dxN09QQlkxUDdHLwp6VEVWNitWMTc2VlNWbmdpWmg4UWs1bldpVE5abHFBRFNXVitlVW5KZnRFL1RJWGhhYzZMeTVIOEpSNkhZZVZCCmlXY3JzdzVKelV6S1NHNGlwL1FDUXUzTGpsVXRzUlRaZlU3WTBjN210YTRYNllndzlyUVpscjl5cGhHdHlkb3UKOEZOaDVDb3RQSVBVV1R5QWxoeEV3YkVEcEtwQS9uSmtKRGdoRzNUdzg0bjU5L0xEVXVES0ZoL3d1OS9sRktVcAp4aVRGQTVPaWxBbC9ndzVyOEYzeVRZakRvTmVqOTczZUdLeUpQL0dpVmVlb2JkeGdVdERXbDFPTGtCQ3I1b2NICnBWSXYxNCtkUXNSRGZKeGFpd29KTlIySjJuS1ljR0lLK1dVdkVUWEFTZDVkb1FJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQp2R1MrUDE1NTZ4MVpHMUhLakxtY2EwMkNXYWxkWDJmZm4ra2pkY3ZHNFl4blpiOWZzUkFYYVROeXp3WWdQM05zClR2UUZrL0tyZnN6QU1uWU1jNXYrTTV0UHhrQ1lvMnNmMHI2OFVNTVJWWEFmd1B2aDNsSHExNXVveU51bkFjRU4Ka0FtTWJiVm56L0FIR3RGL1FSaU1GL0hPaUsxcE1sVm5rRVhpYkRKOFlHa1lYTlNHak5xVHVyRjZQNXJ1d05LaApsVjFlc0lPbXFJY0R5WHF4aksxVHIwdThnSW9HWUNGcE1CczNGZDBHeFErZll3WmRhME0vN0VmdkJ2VmRjU3R3CmRobDlzb3FOS01rbkZqV1dNajlJcDEwOWtWM2h0YzRNWStkemVQY0JNZVJmaXI3NnJpWkY4UWl1NStqaEZCMU0KWURuemR2eXBJMHAvWVcxb25GazFDZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.187.119.199
  name: gke_dev-europe-west1-200515_europe-west1-b_dev-europe-west1
contexts:
- context:
    cluster: gke_dev-europe-west1-200515_europe-west1-b_dev-europe-west1
    user: gke_dev-europe-west1-200515_europe-west1-b_dev-europe-west1
  name: gke_dev-europe-west1-200515_europe-west1-b_dev-europe-west1
current-context: ""
kind: Config
preferences:
  colors: true
users:
- name: gke_dev-europe-west1-200515_europe-west1-b_dev-europe-west1
  user:
    auth-provider:
      config:
        access-token: ya29.a0ARrdaM8IkHrUC4vjyFfezPB5fRDZ1sgqrYvAVOa6-Vb_7D2J12w0yvEi5hYBhNscM6VcunvGjVZeRCOkynA7EPb3j3dBLGGNhEPVQZcnty5JyW3b3gm0hzCWmCWUR8A5K4M92PvnENFbVB29NqycJgclArsiAwH5VW-Ljq0
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2021-10-21T13:39:36Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
