#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

test_fmt() {
  hash terraform 2>&- || { printf >&2 "${RED}terraform not in PATH.${NC}\n"; exit 1; }
  IFS='
  '
  for file in `git diff --cached --name-only --diff-filter=ACM | grep '\.tf$'`
  do
    output=`terraform fmt --check $file 2>&1`
    if test $? -ne 0
    then
      list="${list}${file}\n"
    fi
  done
  exitcode=0
  if test -n "$list"
  then
    printf >&2 "${RED}terraform fmt needs to format these files (run terraform fmt --recursive and git add):${NC}\n"
    printf "$list"
    exitcode=1
  fi
  exit $exitcode
}

test_fmt
