apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNRjlldVdzZ2xwdkNyczczR01BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalF3TmpBNE1UVXpNVEkzV2hjTk16UXdOakE0TVRVegpNVEkzV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBckt1ODlSSmgva0NPNTVkQzNoL2ZueFA1VVBWVXRUR2d6TjBXb2wvRnVzZHEKNFFWc3p4LzBtRTVVVmVHblVRTXphb2s4ZkhEUmt0RlNuTi9sWlQxZW84eTZIL2c3WW1BS3Y1UitzMGtWZy85bAphaVgrcE5oRWxnTzUvNWFIUE4yU3pGZ3dIOGozUEdndXdJQ05Fb1BpS1QvWlo2U1VFakRidWQrVTJudEFLNVJJCjFWaVpoTzBKa0hvcHdldGpNdnZtTmxaRThkYnlGaEZNK2p1YVVRMkZHOFRnOFJJRW0yN1RRWkpmQVdDVWlienUKUDVqQXJITGxSOHQ4MG5TR3ZxUExUNjJYcnRVTHI2d2RnQlFoZlJVK05xbUt2VzMzZmdGNlJxUFNBbGQ2OGZEKwpnMytJOGxaYUhUMFpYUmRLbDZHUWZaSlorRnl5clAxb2FjR2J0anJtQVFJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRJTTBPclM4eDNKRmdGbTMKK2tGT1BoQ3ZTQ1l3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUlGRnIzV3I4L0xyTk1Pcktvcll5TkZHL1hkZgphaGs0UmdPcncrMkc4NDZQY0ZsSUhPaTRBM252WVhVVDBBR1MvdmhGTlovaDlDVVp1QnljSVQ5ZEpoVGdHWDNTCkw0TnRRUEF5ZWdYamFDcjhlOVhOQy9sbjM2ajRmOU9zM3NTTDAxV2pNcWZ5c21RU1ArRUkzdTdlSGJENG9JeVkKTVBObWZ2aU9PMUNhc0luOHNDR1g0d0ZLeExYZThmcFM1RklIdmNrbjVIUEJvNXNoSnc2NjFaMUtpaFh2MzhhUwpVR2F5M1ZwZE8xa0tyeG9WTWNlaGpzbGMxQXVVdWg1Z0cxY3hqVkZPbUhCS2NJM0M3UUg5QmVzOEZGZVJISWNPCmJNTnU5R0ZrbkFsT21IZERyWFUxNUFwOFRudGIxWUdSTVRTSGpLRER0ak9ScFMxRWNTdmxtR2pQZmtFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.k8s.staging.product-tale.com
    name: k8s.staging.product-tale.com
contexts:
  - context:
      cluster: k8s.staging.product-tale.com
      user: k8s.staging.product-tale.com
    name: k8s.staging.product-tale.com
current-context: k8s.staging.product-tale.com
kind: Config
preferences: { }
users:
  - name: k8s.staging.product-tale.com
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - eks
          - get-token
          - --cluster-name
          - k8s.staging.product-tale.com
        command: aws

