apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNRnRjU2l2c1R3K2dZaXBjYk1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05Nakl3TWpJek1UVTFOakUzV2hjTk16SXdNakl6TVRVMQpOakUzV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdUxDcHNlcEVyYy9udVpwTCtDclROenR0Zlhsa2l2MVo3VzluN29GQkVSTnEKVkJ6NUhxemgycGgxN2lES0ZRWG0vQWVOZWpvTDdZRTRXa1ViOWtnUmJQUGJQZHRIZ1VvR3pmSGhsREJkbzUwbQpZRzN0Tlh6cTBzYWdtSUd5aC9scFJtcGZOUFU4bEJnWDBIWFBOVHl4ZlY2TzhmcjJqajgzczU3WXlTVTN2RXJlClV1REtuTnNDT3RQSHNzOHRyeGdrRll3c3AwcklIQzVxQ3l3V1YzcmNyc1VLM29zako2Rk1hMFdnNWtPTGloZG8Kdm8rUFNyMERuQXFwMjJyb3pRTFhxNkdFMlRmQUN3eG1ZYVFQRkdtMlZrNW9mUU9rVi95QURMNlcvMDl3VXZ1bgphU04ydi9DQ0lNZnBsVjZqbXVJZVlaOTBOdVU4SWpvOVk2dDlyTEJ3cHdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVh0WHNleFdpZG0yV3lTUkgKVU9NNVFZTkhNSFV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUc5ZS9hem1RbEJFZlRJUktMbXk2b1NpTjlRUgp0NEhGa3FvVFV3cEdFQmw5MnhoTnJDaktjeWw2bUdnYmlpS1VFL2Q4MGNtWFRnd1VrSG1BL2xRQjlEbmsxL0ZaCkZvcGNmVlljdzF1UU5ubFh3elNFMDNxSFhLZGY1cGkzMVRldDN5YUI2dlI3WGp3Yzd0bjUzVW05d0pBRW1CZ0kKMytWd2JoZG4ydklDZFBOT1ZoTFA0RWpZeUsvdlQzdXN6STZGWnoxb1BxY3VuV3ljZURwSmYrM1lOSU1sbGsrdwppWWRpSWFEM2dvSUFsblYraFpIc3ZBVThYdzd0dlVxOHJwd0N6TmgxU1ZXREFpQXJnSHJUdGRhU1UzYzdoNE5kClRKSDN2NDFiMU5iU3lRczhoS0s2NXMzQnFkdStyKzk0emhTWk12bkIwT2RjTEV6Y3RHL3FET2l6VVhFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.k8s.goodfeed.io
  name: k8s.goodfeed.io
contexts:
- context:
    cluster: k8s.goodfeed.io
    user: k8s.goodfeed.io
  name: k8s.goodfeed.io
kind: Config
preferences: {}
users:
- name: k8s.goodfeed.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - k8s.goodfeed.io
      command: aws-iam-authenticator
      interactiveMode: IfAvailable
      provideClusterInfo: false
