apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lNRnV3c281Rmx4amh6YXlRVU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1qSXdOVEF6TURrMU1EUTBXaGNOTXpJd05UQXlNRGsxTURRMApXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXh5S2tTOXluNllZR0VzNEVWcnYycFZKMXdjS1J3QXZiMW9MTnBBMldEWFdtSmhjb0FWNUsKN2g3Rm5pMlJTWGFMc2RZU05YVTg1TklOcncvRnhKU0tUQjZZMU5pTys4cGJRZVVjdXVHdG1FZm83Wit5REFGcApKSCszNFQySmdVMFU5OSt0MlF5eDNGWU1oVG91LzRUdTExNDFXVW90aXpEQTlLby9PYXNIUW14c3lBN2gwdXpFCmdhVy80RzJDanFpRzhwdURRRGFTMmVzUjhmdnRpRGRQSFp2ZWJSVzJ3UkNHNjFTL0RmS0RtQXNMa3JnNTN3a2oKUXRldkNQL2tWSTl6cFllYzZ5L1NYblRyRlhFemdKbmFMKzZZTFR0YUl6SHJkbXdwekZSU1ppbkhSVG1lYUMzbQpMV01ibWtMN3AxUC8zZldLdTltQURCNUxLSTQ5emdIeWJ3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVyaktJQVFuQVFGaU5BS2c3U2dZRTduVy8KK3Rvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKSnpKT2tJT1ZLcEZTNC96VkE3cU1Ha09qWXpGdGNsU0tTYgpaZ1ZmYW9qVlZGVnVNVlc1MWlpU2NSTGJ3ajJKQ1FmZUFmYmdyNUN0azIvQStDNUtlaXJ4dllpQlY1TTBQUTJNClE3bDhPUXpScDF4N3YvVE05OWxlM3FxR3RmdWF5TE8wWVN5S1phaDRESjdMdXBFWXdvdE0vMDVEQVF4V3VsenUKVkl0OHl4OWN6Vkp3UUg3c3NJNUNqcWt3RytnZ3k3NGVVY1IrOXpQSDE3NWxsL3V6ZU5yeUxRenl3SU5yZy9CSQp4SG9aNGdhWnE0TWN1STBGSWxVR1ExRDNva0JuTVdDaHB4a1VoSmEyV3dHeHJZd0UyYVc5S1FaYWNBVGordHE5CkVhditVYTYxQjg2UnpFTUlpTWtIWUY1ZVNWdHkzclhvcDBIamNYMmh6MXNBQmV1R28rZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://api.k8s.test.plint.dev
    name: k8s.test.plint.dev
contexts:
  - context:
      cluster: k8s.test.plint.dev
      user: k8s.test.plint.dev
    name: k8s.test.plint.dev
current-context: k8s.test.plint.dev
kind: Config
preferences: {}
users:
  - name: k8s.test.plint.dev
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - eks
          - get-token
          - --cluster-name
          - k8s.test.plint.dev
        env:
          - name: AWS_PROFILE
            value: plint-test
        command: aws
