apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lNRnNFc1l4d1ZBREJGc0U2Yk1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1qRXhNakUwTURjME1qSXpXaGNOTXpFeE1qRTBNRGMwTWpJegpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXM5Ukc1NjFJWEZyRUFnOGxyWXp1R2lyTkpTMktCbnFLbnRUUHdkYUlPdEJ0SXI3WGxkUE4KTWVDZUpRbmd3aVVyME9YZ3NlQjUyUmJ6OWtXdjhBSy9zdGptcUFZc2Vnb0ZlS2txdUhSTWFxRkM2V1hUOTcxNQpCM1FRc3IxSHo2eitVZmZFclR1bzhOYkNtVllwK0tJb2RDVDQ5TXkzUTFDc3VITWptQjdVbXhWMUNwSTY4UmtYCnFxNHNXMnFDWklySHJMR1g3M0NLcUYzSUh0VnVORGNCV1NUTEZhaHVleDJqM0ROREdLQ1FpSHl3anRleDJrUlgKZTU5V1pJekNnWlVjemdIUzkwZnM3Z1BNWmJvUm5QMEpZRW5EZ0UyYm56eWpXeEsrUUt2czcxdzlETWNvWVc4WgpIbTlsa2lMOW1wOWNhM3lmV2phclZLcUJ5RlF6M3Vra213SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVzNERQTnhyenVZbTZ3c2E1N05QS25DWUYKamxJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDV1d3cDBmVko2YldvdFZoYTN1Ynd4YzJjclBwNmpKOXFnZQpkOHFKOTZiQytMZnBqRjlwNnNuRzBYeEpCSW1PWFcrcDQ2LzVnWEIyTHJLaWpCVWlEUG12KzRNbUFZSzFCeWxTCkVGenljK0w3M3k4Zk9uYjNrTzVjY1R3TjAxUm1tbXpBUnNPUW1VcVl5cFdXKyt6K3dJZFNkK2F4dWpWOVVHd2sKSmk2VHVVNzBBZnlLc3ppNXFvTTVjc21uelNsY2FNeHZZWmdHdGM1K3RtRlJUT2NuUUlzaFc0bEVhM2s5NURHSwpGY1lhTEJDd2sxRVVMcGVpQjhVSmtpRVkwUlYwbFdrZVhUNmJwdmJKYUJCRFBiTHJ5NW9pOERXSXRoYUNzcER3CnNqdC9kTUFXMU1FWWNSUHFLZjRZMjVSYzZ6dklTY3oxbFA1bXpvWkNxMklLTUpZb2lIWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://api.k8s.sprint.plint.dev
  name: k8s.sprint.plint.dev
contexts:
- context:
    cluster: k8s.sprint.plint.dev
    user: k8s.sprint.plint.dev
  name: k8s.sprint.plint.dev
current-context: k8s.sprint.plint.dev
kind: Config
preferences: {}
users:
- name: k8s.sprint.plint.dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - k8s.sprint.plint.dev
      command: aws-iam-authenticator
